MILKDROP_PRESET_VERSION=201
PSVERSION=2
PSVERSION_WARP=2
PSVERSION_COMP=2

[preset00]
fShader=0.0
fGammaAdj=1.980
warp=0
zoom=1

# disable built-in wave
wave_a=0

shapecode_0_enabled=1
shapecode_0_sides=3
shapecode_0_rad=0.1

shapecode_0_r=1

shape_0_per_frame='''
    x = q1;
    y = q2;
    ang = -time;
'''

per_frame_init_='''
    x0 = .25 + rand(10)/20;
    y0 = .25 + rand(10)/20;
    vx0 = .25 - rand(10)/20;
    vy0 = .25 - rand(10)/20;

    x1 = .25 + rand(10)/20;
    y1 = .25 + rand(10)/20;
    vx1 = .25 - rand(10)/20;
    vy1 = .25 - rand(10)/20;

    # average of positions should be at (.5, .5)
    x2 = 1.5 - x0 - x1;
    y2 = 1.5 - y0 - y1;

    # average of velocities should be 0
    vx2 = -vx0 - vx1;
    vy2 = -vy0 - vy1;

    last_time = time;
'''

# F = GMm/r

per_frame_='''
    dt = time - last_time;
    last_time = time;

    x0 = x0 + vx0*dt;
    y0 = y0 + vy0*dt;

    x1 = x1 + vx1*dt;
    y1 = y1 + vy1*dt;

    x2 = x2 + vx2*dt;
    y2 = y2 + vy2*dt;

    vx0 = vx0 + .2*(x1 - x0)*dt + .2*(x2 - x0)*dt + .1*(.5 - x0)*dt;
    vy0 = vy0 + .2*(y1 - y0)*dt + .2*(y2 - y0)*dt + .1*(.5 - y0)*dt;

    vx1 = vx1 + .2*(x0 - x1)*dt + .2*(x2 - x1)*dt + .1*(.5 - x1)*dt;
    vy1 = vy1 + .2*(y0 - y1)*dt + .2*(y2 - y1)*dt + .1*(.5 - y1)*dt;

    vx2 = vx2 + .2*(x0 - x2)*dt + .2*(x1 - x2)*dt + .1*(.5 - x2)*dt;
    vy2 = vy2 + .2*(y0 - y2)*dt + .2*(y1 - y2)*dt + .1*(.5 - y2)*dt;

    q1 = x0;
    q2 = y0;

    q3 = x1;
    q4 = y1;

    q5 = x2;
    q6 = y2;

    q8 = dt;
'''

warp_='''
    shader_body {
        ret = tex2D(sampler_main, uv);
    }
'''
comp_='''
    shader_body {
        // ret = tex2D(sampler_main, uv);

        float cutoff = 100;

        float2 d1 = uv - float2(q1,q2);
        float2 d2 = uv - float2(q3,q4);
        float2 d3 = uv - float2(q5,q6);

        float pot = 1/dot(d1,d1) + 1/dot(d2,d2) + 1/dot(d3,d3);
        if (pot > cutoff) {
            ret.z = 1/sqrt(pot - cutoff);
        }
    }
'''

