MILKDROP_PRESET_VERSION=201
PSVERSION=2
PSVERSION_WARP=2
PSVERSION_COMP=2
[preset00]
warp=0.00000
sx=1.00000
sy=1.00000
wave_r=0.000
wave_g=0.300
wave_b=0.500
wave_x=0.500
wave_y=0.500
ob_size=0.005
ob_r=0.000
ob_g=0.000
ob_b=0.000
ob_a=1.000
ib_size=0.010
ib_r=0.250
ib_g=0.250
ib_b=0.250
ib_a=0.000
nMotionVectorsX=64.000
nMotionVectorsY=48.000
mv_dx=0.000
mv_dy=0.000
mv_l=0.000
mv_r=1.000
mv_g=1.000
mv_b=1.000
mv_a=0.100
b1n=0.000
b2n=0.000
b3n=0.000
b1x=1.000
b2x=1.000
b3x=1.000
b1ed=0.250
wavecode_0_enabled=1
wavecode_0_samples=512
wavecode_0_sep=0
wavecode_0_bSpectrum=0
wavecode_0_bUseDots=1
wavecode_0_bDrawThick=1
wavecode_0_bAdditive=1
wavecode_0_scaling=1.00000
wavecode_0_smoothing=0.50000
wavecode_0_r=1.000
wavecode_0_g=1.000
wavecode_0_b=1.000
wavecode_0_a=1.000
wave_0_per_point='''
    tscale=.45+(bass*.02);
    trot=3;
    a=above(sample,0);
    
    tp1x=.5+(cos(3.1415*0+(time*trot))*tscale*.75);
    tp1y=.5+(sin(3.1415*0+(time*trot))*tscale);
    
    tp2x=.5+(cos(3.1415*.6667+(time*trot))*tscale*.75);
    tp2y=.5+(sin(3.1415*.6667+(time*trot))*tscale*sin(time)); //spin
    
    tp3x=.5+(cos(3.1415*1.3333+(time*trot))*tscale*.75);
    tp3y=.5+(sin(3.1415*1.3333+(time*trot))*tscale*sin(time)); //spin
    
    
    //draw via random walk
    tri_point=rand(3);
    
    //point 1
    t_x=t_x+(equal(tri_point,0)*(tp1x-t_x)*.5);
    t_y=t_y+(equal(tri_point,0)*(tp1y-t_y)*.5);
    
    //point 2
    t_x=t_x+(equal(tri_point,1)*(tp2x-t_x)*.5);
    t_y=t_y+(equal(tri_point,1)*(tp2y-t_y)*.5);
    
    //point 3
    t_x=t_x+(equal(tri_point,2)*(tp3x-t_x)*.5);
    t_y=t_y+(equal(tri_point,2)*(tp3y-t_y)*.5);
    
    x=t_x;
    y=t_y;
'''
wavecode_1_enabled=1
wavecode_1_samples=512
wavecode_1_sep=0
wavecode_1_bSpectrum=0
wavecode_1_bUseDots=1
wavecode_1_bDrawThick=1
wavecode_1_bAdditive=1
wavecode_1_scaling=1.00000
wavecode_1_smoothing=0.50000
wavecode_1_r=1.000
wavecode_1_g=1.000
wavecode_1_b=1.000
wavecode_1_a=1.000
wave_1_per_point='''
    tscale=.45+(bass*.02);
    trot=3;
    a=above(sample,0);
    
    tp1x=.5+(cos(3.1415*0+(time*trot))*tscale*.75);
    tp1y=.5+(sin(3.1415*0+(time*trot))*tscale);
    
    tp2x=.5+(cos(3.1415*.6667+(time*trot))*tscale*.75);
    tp2y=.5+(sin(3.1415*.6667+(time*trot))*tscale*sin(time)); //spin
    
    tp3x=.5+(cos(3.1415*1.3333+(time*trot))*tscale*.75);
    tp3y=.5+(sin(3.1415*1.3333+(time*trot))*tscale*sin(time)); //spin
    
    
    //draw via random walk
    tri_point=rand(3);
    
    //point 1
    t_x=t_x+(equal(tri_point,0)*(tp1x-t_x)*.5);
    t_y=t_y+(equal(tri_point,0)*(tp1y-t_y)*.5);
    
    //point 2
    t_x=t_x+(equal(tri_point,1)*(tp2x-t_x)*.5);
    t_y=t_y+(equal(tri_point,1)*(tp2y-t_y)*.5);
    
    //point 3
    t_x=t_x+(equal(tri_point,2)*(tp3x-t_x)*.5);
    t_y=t_y+(equal(tri_point,2)*(tp3y-t_y)*.5);
    
    x=t_x;
    y=t_y;
'''
wavecode_2_enabled=1
wavecode_2_samples=512
wavecode_2_sep=0
wavecode_2_bSpectrum=0
wavecode_2_bUseDots=1
wavecode_2_bDrawThick=1
wavecode_2_bAdditive=1
wavecode_2_scaling=1.00000
wavecode_2_smoothing=0.50000
wavecode_2_r=1.000
wavecode_2_g=1.000
wavecode_2_b=1.000
wavecode_2_a=1.000
wave_2_per_point='''
    tscale=.45+(bass*.02);
    trot=3;
    a=above(sample,0);
    
    tp1x=.5+(cos(3.1415*0+(time*trot))*tscale*.75);
    tp1y=.5+(sin(3.1415*0+(time*trot))*tscale);
    
    tp2x=.5+(cos(3.1415*.6667+(time*trot))*tscale*.75);
    tp2y=.5+(sin(3.1415*.6667+(time*trot))*tscale*sin(time)); //spin
    
    tp3x=.5+(cos(3.1415*1.3333+(time*trot))*tscale*.75);
    tp3y=.5+(sin(3.1415*1.3333+(time*trot))*tscale*sin(time)); //spin
    
    
    //draw via random walk
    tri_point=rand(3);
    
    //point 1
    t_x=t_x+(equal(tri_point,0)*(tp1x-t_x)*.5);
    t_y=t_y+(equal(tri_point,0)*(tp1y-t_y)*.5);
    
    //point 2
    t_x=t_x+(equal(tri_point,1)*(tp2x-t_x)*.5);
    t_y=t_y+(equal(tri_point,1)*(tp2y-t_y)*.5);
    
    //point 3
    t_x=t_x+(equal(tri_point,2)*(tp3x-t_x)*.5);
    t_y=t_y+(equal(tri_point,2)*(tp3y-t_y)*.5);
    
    x=t_x;
    y=t_y;
'''
wavecode_3_enabled=1
wavecode_3_samples=512
wavecode_3_sep=0
wavecode_3_bSpectrum=0
wavecode_3_bUseDots=1
wavecode_3_bDrawThick=1
wavecode_3_bAdditive=1
wavecode_3_scaling=1.00000
wavecode_3_smoothing=0.50000
wavecode_3_r=1.000
wavecode_3_g=1.000
wavecode_3_b=1.000
wavecode_3_a=1.000
wave_3_per_point='''
    tscale=.45+(bass*.02);
    trot=3;
    a=above(sample,0);
    
    tp1x=.5+(cos(3.1415*0+(time*trot))*tscale*.75);
    tp1y=.5+(sin(3.1415*0+(time*trot))*tscale);
    
    tp2x=.5+(cos(3.1415*.6667+(time*trot))*tscale*.75);
    tp2y=.5+(sin(3.1415*.6667+(time*trot))*tscale*sin(time)); //spin
    
    tp3x=.5+(cos(3.1415*1.3333+(time*trot))*tscale*.75);
    tp3y=.5+(sin(3.1415*1.3333+(time*trot))*tscale*sin(time)); //spin
    
    
    //draw via random walk
    tri_point=rand(3);
    
    //point 1
    t_x=t_x+(equal(tri_point,0)*(tp1x-t_x)*.5);
    t_y=t_y+(equal(tri_point,0)*(tp1y-t_y)*.5);
    
    //point 2
    t_x=t_x+(equal(tri_point,1)*(tp2x-t_x)*.5);
    t_y=t_y+(equal(tri_point,1)*(tp2y-t_y)*.5);
    
    //point 3
    t_x=t_x+(equal(tri_point,2)*(tp3x-t_x)*.5);
    t_y=t_y+(equal(tri_point,2)*(tp3y-t_y)*.5);
    
    x=t_x;
    y=t_y;
'''
shapecode_0_enabled=1
shapecode_0_sides=30
shapecode_0_additive=0
shapecode_0_thickOutline=0
shapecode_0_textured=1
shapecode_0_num_inst=1
shapecode_0_x=0.240
shapecode_0_y=0.500
shapecode_0_rad=0.47209
shapecode_0_ang=0.00000
shapecode_0_tex_ang=0.62832
shapecode_0_tex_zoom=0.81952
shapecode_0_r=0.600
shapecode_0_g=0.600
shapecode_0_b=0.900
shapecode_0_a=0.000
shapecode_0_border_r=1.000
shapecode_0_border_g=1.000
shapecode_0_border_b=1.000
shapecode_0_border_a=0.000
shape_0_per_frame='''
    x=(sin(time*.5)*.5)+.5;
'''
shapecode_1_enabled=1
shapecode_1_sides=4
shapecode_1_additive=1
shapecode_1_thickOutline=0
shapecode_1_textured=1
shapecode_1_num_inst=1
shapecode_1_x=0.500
shapecode_1_y=0.500
shapecode_1_rad=1.79142
shapecode_1_ang=0.00000
shapecode_1_tex_ang=1.57080
shapecode_1_tex_zoom=1.00000
shapecode_1_r=0.300
shapecode_1_g=0.200
shapecode_1_b=0.800
shapecode_1_a=0.000
shapecode_1_border_r=1.000
shapecode_1_border_g=1.000
shapecode_1_border_b=1.000
shapecode_1_border_a=0.000
shapecode_2_enabled=1
shapecode_2_sides=4
shapecode_2_additive=0
shapecode_2_thickOutline=0
shapecode_2_textured=1
shapecode_2_num_inst=1
shapecode_2_x=0.500
shapecode_2_y=0.500
shapecode_2_rad=0.80814
shapecode_2_ang=0.00000
shapecode_2_tex_ang=0.00000
shapecode_2_tex_zoom=1.00000
shapecode_2_r=0.700
shapecode_2_g=0.600
shapecode_2_b=0.500
shapecode_2_a=0.000
shapecode_2_border_r=1.000
shapecode_2_border_g=1.000
shapecode_2_border_b=1.000
shapecode_2_border_a=0.000
shapecode_3_enabled=1
shapecode_3_sides=100
shapecode_3_additive=0
shapecode_3_thickOutline=0
shapecode_3_textured=1
shapecode_3_num_inst=1
shapecode_3_x=0.500
shapecode_3_y=0.500
shapecode_3_rad=0.36457
shapecode_3_ang=0.00000
shapecode_3_tex_ang=0.00000
shapecode_3_tex_zoom=0.49831
shapecode_3_r=0.000
shapecode_3_g=1.000
shapecode_3_b=0.000
shapecode_3_a=0.800
shapecode_3_border_r=1.000
shapecode_3_border_g=1.000
shapecode_3_border_b=1.000
shapecode_3_border_a=0.100
per_frame_='''
    t = time*12.3;
    //wave_x = wave_x + 0.350*( 0.70*sin(2.221*time*5) + 0.30*sin(1.821*time*15) );
    //wave_y = wave_y + 0.350*( 0.30*sin(1.942*time*5) + 0.70*sin(2.522*time*15) );
    //wave_r = wave_r + 0.790*( 0.60*sin(0.823*t) + 0.40*sin(0.916*t) );
    //wave_g = wave_g + 0.790*( 0.60*sin(0.900*t) + 0.40*sin(1.023*t) );
    //wave_b = wave_b + 0.790*( 0.60*sin(0.808*t) + 0.40*sin(0.949*t) );
    rot = rot + 0.030*( 0.60*sin(0.38*time) + 0.40*sin(0.54*time) );
    dx = dx + 0.002*( 0.60*sin(0.434*time) + 0.40*sin(0.277*time) );
    dy = dy + 0.002*( 0.60*sin(0.384*time) + 0.40*sin(0.477*time) );
    //rot = 0;
    //wave_a = 0;
'''
warp_='''
    `sampler sampler_smalltiled_ensign_meat;
    `float4 texsize_smalltiled_ensign_meat;
    `
    `shader_body
    `{
    `    // sample previous frame
    `    ret = tex2D( sampler_fc_main, uv ).xyz;
    `
    `    // this creates an endless texture zoom:
    `    {  // the { } block creates a local, temporary scope for any new variables
    `     float t = frac(time*0.5);
    `     float zoom1 = pow(0.5, t);
    `     float zoom2 = zoom1*2;
    `     float2 uv1 = (uv-0.5) * zoom1 + 0.5;
    `     float2 uv2 = (uv-0.5) * zoom2 + 0.5;    
    `     float3 c  = tex2D(sampler_smalltiled_ensign_meat, 
    `                  uv1*texsize.xy*texsize_smalltiled_ensign_meat.zw).xyz;
    `     float3 c2 = tex2D(sampler_smalltiled_ensign_meat, 
    `                  uv2*texsize.xy*texsize_smalltiled_ensign_meat.zw).xyz;
    `     c = lerp(c, c2, t);
    `     c *= saturate(rad*1.3)*1.1; //darken @ center
    `     ret = lerp(ret, c, 0.15);
    `    }
    `   
    `    // darken over time
    `    ret *= 0.80; //or try: ret -= 0.004;
    `
    `}
'''
comp_='''
    `shader_body
    `{
    `    float2 d = texsize.zw*4;
    `    float1 dx = ( GetBlur1(uv+float2(1,0)*d)-GetBlur1(uv-float2(1,0)*d) ).y;
    `    float1 dy = ( GetBlur1(uv+float2(0,1)*d)-GetBlur1(uv-float2(0,1)*d) ).y;
    `    float2 uv_y = uv-float2(dx,dy)*0.4;
    `
    `ret = lerp(tex2D(sampler_fc_main, uv_y).x*pow(hue_shader.zxy,2),
    `           lerp(pow(hue_shader,4)*1.2,3,GetPixel(uv).z),
    `           GetBlur1(uv).y);
    `}
    `
'''
