MILKDROP_PRESET_VERSION=201
PSVERSION=2
PSVERSION_WARP=2
PSVERSION_COMP=2

[preset00]
fShader=0.0
fDecay=1
fGammaAdj=1.980
warp=0
zoom=1

# disable built-in wave
wave_a=0

wavecode_0_enabled=0
wavecode_0_samples=100
wavecode_0_bUseDots=1
wavecode_0_bDrawThick=1
wavecode_0_bAdditive=1

wave_0_per_point='''
'''

warp_='''
    shader_body {
        ret = tex2D(sampler_pc_main, uv + float2(0.0005, 0));
        if (progress < 0.01) {
            ret = 0;
        }
    }
'''

comp_='''
    shader_body {
    float a = (0.5-uv.x);
    float c = uv.x/a;
    float d = uv.y-0.5;
    float e = d*(1+c)+time;
    ret = tex2D(sampler_rand0, float2(c,e));
    }
'''

