MILKDROP_PRESET_VERSION=201
PSVERSION=2
PSVERSION_WARP=2
PSVERSION_COMP=2

[preset00]
fDecay=1.500000
fShader=0.000000
warp=0
zoom=1.0001

# disable built-in wave
fWaveAlpha=0

# custom wave
wavecode_1_enabled=1
wavecode_1_samples=512
wavecode_1_bSpectrum=1
wavecode_1_bUseDots=0
wavecode_1_bDrawThick=1
wave_1_per_point='''
    x=sample;
    y=.5 + .25*sin(time + sample*10)*log(1+bass_att);
    a=1;
    r=bass_att;
    g=mid_att;
    b=treb_att;
'''

warp_='''
    shader_body {
        ret = tex2D(sampler_main, uv);
    }
'''

comp_='''
    shader_body {
        ret = tex2D(sampler_main, uv);
    }
'''
